### ISSUE TITLE
Countdown timer doesn't speed up with time warp.

### ISSUE THREAD

**Issue by enceos** [BrettWebb/KerbalSmartParts#2]
The timer allows to plan things even 120+ mins ahead, but after you set it to do so, you can't warp to the timed action, you gotta wait dem 120 mins!

Very inconvenient when you plan actions for RemoteTech probes which go out of comm range.

**Comment by NobodysNightmare** [comment]
Seems that the code of smart parts is using the time of the unity simulation, rather than game time.

I have a fix that is working locally with other drawbacks. I'll have to get some things straight and will provide a PR that should fix the issue... I guess ^^

**Comment by enceos** [comment]
Thank you so much, I haven't seen mr. Firov (Brett Webb) for over a month. Would you be kind to compile the .dll with this fix?

**Comment by NobodysNightmare** [comment]
I uploaded the bare DLL under https://github.com/NobodysNightmare/KerbalSmartParts/releases/tag/1.5.1-plus-timer

Note that this is not a real release, but the bare DLL.

I hope that @BrettWebb will soon re-appear, merge my PR and publish an official update.

I don't think that it would be a favorable option if I tried to take over with maintaining this Add-On... But in case more issues pop up and remain unresolved, I will keep that as a fallback option ^^

**Comment by enceos** [comment]
Thank you very much. I believe @BrettWebb will appear when 1.0 comes out. Until then this temporary fix should work nicely :)
